services:
  pgbouncer:
    volumes:
      - ./docker/pgbouncer/pgbouncer.local.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./docker/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro

  migrate:
    env_file:
      - .env.docker.local
    build:
      args:
        DATABASE_URL: ${DATABASE_URL}

  seed:
    env_file:
      - .env.docker.local
    build:
      args:
        DATABASE_URL: ${DATABASE_URL}

  web:
    env_file:
      - .env.docker.local
    build:
      args:
        DATABASE_URL: ${DATABASE_URL}
        AUTH_SECRET: ${AUTH_SECRET}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        AUTH_URL: ${AUTH_URL}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        REDIS_URL: ${REDIS_URL}
